apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend-app-sa

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-app
  labels:
    app: backend-app
spec:
  replicas: 2
  revisionHistoryLimit: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: backend-app
  template:
    metadata:
      labels:
        app: backend-app
    spec:
      serviceAccountName: backend-app-sa
      containers:
        - name: backend-app
          image: 526741672110.dkr.ecr.us-east-1.amazonaws.com/backend-app:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 3000
          envFrom:
            - secretRef:
                name: backend-app-env
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-app
  labels:
    app: backend-app
spec:
  type: LoadBalancer
  selector:
    app: backend-app
  ports:
    - name: http
      port: 80
      targetPort: 3000
      protocol: TCP