apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: backend

resources:
  - namespace.yaml
  - deployment.yaml
  - hpa.yaml
  - secrets.yaml

commonLabels:
  app.kubernetes.io/name: backend-app
  app.kubernetes.io/managed-by: argocd